import React from 'react';
import Breadcrumb from './Breadcrumb';

const BillingView = ({ setView }) => (
  <div className="animate-fade-in max-w-6xl mx-auto pb-20">
    <Breadcrumb current="Billing & Payments" setView={setView} />
    <h2 className="text-4xl font-bold text-gray-900 mb-2 font-serif">Billing & Payment</h2>
    <p className="text-xs text-gray-400 mb-12 leading-relaxed max-w-2xl">Manage your practice's subscription, payment methods, and billing information with clinical precision.</p>
    <div className="flex flex-col lg:flex-row gap-12"><div className="w-full lg:w-96 space-y-6"><div className="bg-white rounded-[2rem] border border-gray-50 shadow-sm overflow-hidden"><div className="p-8 border-b border-gray-25"><h4 className="text-sm font-bold text-gray-900">Payment Methods</h4></div><div className="p-8 space-y-6"><div className="flex items-center justify-between bg-gray-25/50 p-4 rounded-2xl border border-gray-50"><div className="flex items-center gap-4"><div className="w-12 h-8 bg-white border border-gray-100 rounded-lg flex items-center justify-center p-1 shadow-sm"><img src="https://upload.wikimedia.org/wikipedia/commons/5/5e/Visa_Inc._logo.svg" alt="Visa" className="h-2" /></div><div><p className="text-xs font-bold text-gray-700">Visa **** 1234</p><p className="text-[10px] text-gray-400 font-bold uppercase tracking-tight">Expiration: 05/23</p></div></div><div className="flex items-center gap-2"><button className="text-purple-600 text-[10px] font-bold hover:underline">Edit</button><button className="text-gray-300 hover:text-gray-500"><svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20"><path d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z"/></svg></button></div></div><button className="w-full py-4 border-2 border-dashed border-gray-100 rounded-[1.5rem] flex items-center justify-center gap-3 text-gray-400 hover:border-purple-200 hover:text-purple-400 transition-all font-bold text-xs uppercase tracking-widest"><span className="text-xl">+</span> Add Payment Method</button></div></div></div>
      <div className="flex-1 bg-white rounded-[2.5rem] p-12 border border-gray-50 shadow-sm space-y-12"><div><h3 className="text-xl font-bold text-gray-900 mb-8">Add Card</h3><div className="grid grid-cols-1 md:grid-cols-4 gap-6"><div className="md:col-span-4 space-y-2"><label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest ml-1">Card Number</label><div className="relative"><span className="absolute left-5 top-1/2 -translate-y-1/2 text-gray-400"><svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z"/></svg></span><input type="text" placeholder="0000 0000 0000 0000" className="w-full pl-14 pr-6 py-4 bg-gray-25 border border-transparent rounded-2xl text-sm font-mono focus:bg-white focus:border-purple-200 transition-all outline-none" /></div></div><div className="md:col-span-2 space-y-2"><label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest ml-1">Expiry (MM/YY)</label><input type="text" placeholder="MM/YY" className="w-full px-6 py-4 bg-gray-25 border border-transparent rounded-2xl text-sm outline-none focus:bg-white focus:border-purple-200 transition-all" /></div><div className="md:col-span-2 space-y-2"><label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest ml-1">CVV</label><input type="password" placeholder="***" className="w-full px-6 py-4 bg-gray-25 border border-transparent rounded-2xl text-sm outline-none focus:bg-white focus:border-purple-200 transition-all" /></div></div></div>
        <div><h3 className="text-xl font-bold text-gray-900 mb-8">Billing Address</h3><div className="grid grid-cols-1 md:grid-cols-4 gap-6"><div className="md:col-span-4 space-y-2"><label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest ml-1">Full Name</label><input type="text" defaultValue="Dr. Julian Sterling" className="w-full px-6 py-4 bg-gray-25 border border-transparent rounded-2xl text-sm font-bold text-gray-600 outline-none focus:bg-white focus:border-purple-200 transition-all" /></div><div className="md:col-span-2 space-y-2"><label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest ml-1">Country</label><select className="w-full px-6 py-4 bg-gray-25 border border-transparent rounded-2xl text-sm font-bold text-gray-600 outline-none focus:bg-white focus:border-purple-200 transition-all appearance-none cursor-pointer"><option>United States</option><option>Canada</option></select></div><div className="md:col-span-2 space-y-2"><label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest ml-1">City</label><input type="text" defaultValue="San Francisco" className="w-full px-6 py-4 bg-gray-25 border border-transparent rounded-2xl text-sm font-bold text-gray-600 outline-none focus:bg-white focus:border-purple-200 transition-all" /></div><div className="md:col-span-4 space-y-2"><label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest ml-1">Street Address</label><input type="text" defaultValue="123 Clinical Plaza, Suite 400" className="w-full px-6 py-4 bg-gray-25 border border-transparent rounded-2xl text-sm font-bold text-gray-600 outline-none focus:bg-white focus:border-purple-200 transition-all" /></div><div className="md:col-span-2 space-y-2"><label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest ml-1">Province / State</label><input type="text" defaultValue="California" className="w-full px-6 py-4 bg-gray-200/50 border border-transparent rounded-2xl text-sm font-bold text-gray-500 outline-none" /></div><div className="md:col-span-2 space-y-2"><label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest ml-1">Postal Code</label><input type="text" defaultValue="94105" className="w-full px-6 py-4 bg-gray-200/50 border border-transparent rounded-2xl text-sm font-bold text-gray-500 outline-none" /></div></div></div>
        <div className="flex justify-end gap-6 pt-8"><button onClick={() => setView('main')} className="px-10 py-4 text-sm font-bold text-gray-500 hover:text-gray-800 transition-colors">Cancel</button><button onClick={() => setView('main')} className="flex items-center gap-3 px-10 py-4 bg-gradient-to-r from-purple-700 to-purple-500 text-white rounded-2xl font-bold text-sm shadow-xl shadow-purple-200 hover:-translate-y-1 transition-all"><svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M5 13l4 4L19 7"/></svg> Save Changes</button></div>
      </div>
    </div>
  </div>
);

export default BillingView;
